add custom extras

diff --git a/bhyve-api b/bhyve-api
--- a/bhyve-api
+++ b/bhyve-api
@@ -4,9 +4,8 @@ DIST_MODULE_PATH="${distmoduledir}/bhyve.d"
 . ${DIST_MODULE_PATH}/share/bhyve.conf
 
 #OPTARGS="${MYCOL} init_masters init_workers"
-MYOPTARG="imgsize jname img ram cpus pubkey host_hostname"
+MYOPTARG="imgsize jname img ram cpus pubkey host_hostname extras"
 MYARG="mode"
-#MYOPTARG="display header active human bhyve_name dryrun checkip develop runasap header gold"
 MYDESC="Operate with K8S cluster"
 CBSDMODULE="sys"
 # imgsize=10g mode=init jname=test img=ubuntu ram=1g cpus=2
@@ -68,7 +67,110 @@ create_env()
 	[ -z "${vm_os_profile}" ] && err 1 "vm_os_profile empty? check img/mapping in bhyve-api.conf for: ${img}"
 	[ -z "${ssh_user}" ] && err 1 "ssh_user empty? check img/mapping in bhyve-api.conf for: ${img}"
 
-	ip4_addr=$( dhcpd ip4pool=${ip4pool} )
+	# extras area
+	v6_addr=
+	v4_addr=
+	primary_ip=
+	ip4_addr=
+	ossh_port=
+	port=
+
+	if [ -n "${extras}" ]; then
+		# strip special: must be performed on the API first
+		extras=$( echo ${extras} | ${TR_CMD} -dc '[:alnum:]:,\n\r' | ${TR_CMD} '[:upper:]' '[:lower:]' )
+		log "EXTRAS [${extras}]"
+	fi
+
+	exec_extras=
+
+	if [ -n "${extras}" ]; then
+
+		for i in ${jail_known_extras}; do
+			unset ${i}
+		done
+
+		OIFS="${IFS}"
+		IFS=","
+		for i in ${extras}; do
+			IFS="${OIFS}"
+			extras_name=$( echo ${i} | cut -d ":" -f 1 )
+			known=0
+			for x in ${jail_known_extras}; do
+				log "extras check [${x}][${extras_name}]"
+				if [ "${x}" = "${extras_name}" ]; then
+					known=1
+				fi
+			done
+
+			if [ ${known} -eq 1 ]; then
+				#extras_val=$( echo ${i} | cut -d ":" -f 2 )
+				_arg_len=$( strlen ${i} )
+				strpos --str="${i}" --search=":"
+				_eqpos=$?
+				_eqpos=$(( _eqpos + 2 ))
+				extras_val=$( substr --pos=${_eqpos} --len=${_arg_len} --str="${i}" )
+				log "known extras found: ${extras_name}, val: [${extras_val}]"
+				eval "${extras_name}=\"${extras_val}\""
+
+				if [ -z "${exec_extras}" ]; then
+					exec_extras="${extras_name}"
+				else
+					exec_extras="${exec_extras} ${extras_name}"
+				fi
+			else
+				log "Unknown extras: ${extras_name}"
+			fi
+			IFS=","
+		done
+		IFS="${OIFS}"
+
+		if [ "${ipv6}" = "external" ]; then
+			v6_addr=$( dhcpdv6 )
+			primary_ip="${v6_addr}"
+			ssh_host="${primary_ip}"
+			ossh_port="22"
+			v4_addr=$( dhcpd ip4pool=${ip4pool} )
+		else
+			v4_addr=$( dhcpd ip4pool=${ip4pool} )
+			primary_ip="${v4_addr}"
+		fi
+	else
+		v4_addr=$( dhcpd ip4pool=${ip4pool} )
+		primary_ip="${v4_addr}"
+	fi
+
+	log "exec extras: ${exec_extras}"
+
+	for i in ${exec_extras}; do
+		log "looking for helper : ${i}"
+		#helper_var="extras_helper_${i}"
+		#log "looking for helper : ${helper_var}"
+		#eval helper="\$helper_var"
+
+		eval helper="\$extras_helper_$i"
+
+		if [ -x "${helper}" ]; then
+			log "HELPER FOUND for ${i}: [${helper}]"
+			letsencrypt_args=
+			[ -n "${letsencrypt}" ] && letsencrypt_args="-l true"
+			log "EXEC HELPER: ${helper} -m create -n \"${lb}\" -a \"${v4_addr}\" -b \"${v6_addr}\" ${letsencrypt_args}"
+			${helper} -m create -n "${lb}" -a "${v4_addr}" -b "${v6_addr}" ${letsencrypt_args} >> ${MY_LOG} 2>&1
+			ret=$?
+			# todo: notify for error
+		else
+			log "HELPER for ${i} not found: ${helper}!"
+		fi
+	done
+
+	for i in ${v6_addr} ${v4_addr}; do
+		if [ -z "${ip4_addr}" ]; then
+			ip4_addr="${i}"
+		else
+			ip4_addr="${ip4_addr},${i}"
+		fi
+	done
+
+	#ip4_addr=$( dhcpd ip4pool=${ip4pool} )
 	[ -z "${ip4_gw}" ] && ip4_gw="10.0.0.1"
 	ci_jname="${jname}"
 
@@ -184,6 +286,10 @@ ci_jname=\"${ci_fqdn}\" \
 	fi
 
 	create_time=$( ${DATE_CMD} -u "+%Y-%m-%dT%H:%M:%S" )
+	[ -z "${port4}" ] && port4="${port}"
+	[ -z "${port6}" ] && port6="${port}"
+	[ -z "${ssh4_host}" ] && ssh4_host="${v4_addr}"
+	[ -z "${ssh6_host}" ] && ssh6_host="${v6_addr}"
 
 	#echo "${host_hostname} (${vm_os_type}:${vm_os_profile}) ${cpus}/${ram}/${imgsize} ssh ${ssh_user}@${ssh_host} -p${port}" > ${cbsd_api_dbdir}/${cid}/vms/${jname}
 
@@ -205,8 +311,14 @@ ci_jname=\"${ci_fqdn}\" \
   "vm_os_profile": "${vm_os_profile}",
   "ssh_user": "${ssh_user}",
   "ssh_host": "${ssh_host}",
+  "ssh4_host": "${ssh4_host}",
+  "ssh6_host": "${ssh6_host}",
   "ssh_port": ${port},
-  "ssh_string": "ssh ${ssh_user}@${ssh_host} -p${port}"
+  "ssh4_port": ${port4},
+  "ssh6_port": ${port6},
+  "ssh_string": "ssh ${ssh_user}@${ssh_host} -p${port}",
+  "ssh4_string": "ssh ${ssh_user}@${ssh4_host} -p${port4}",
+  "ssh6_string": "ssh ${ssh_user}@${ssh6_host} -p${port6}"
 }
 EOF
         # dup to param-values
@@ -226,8 +338,14 @@ vm_os_type="${vm_os_type}"
 vm_os_profile="${vm_os_profile}"
 ssh_user="${ssh_user}"
 ssh_host="${ssh_host}"
+ssh4_host="${ssh4_host}"
+ssh6_host="${ssh6_host}"
 ssh_port="${port}"
+ssh_port4="${port4}"
+ssh_port6="${port6}"
 ssh_string="ssh ${ssh_user}@${ssh_host} -p${port}"
+ssh4_string="ssh ${ssh_user}@${ssh4_host} -p${port4}"
+ssh6_string="ssh ${ssh_user}@${ssh6_host} -p${port6}"
 EOF
 
 	${CHOWN_CMD} ${cbsduser}:${cbsduser} ${cbsd_api_dbdir}/${cid}/vms/${jname} ${cbsd_api_dbdir}/${cid}/${jname}.node ${cbsd_api_dbdir}/${cid}/${jname}-bhyve.ssh
